# Generated by Django 5.2.8 on 2025-11-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobby',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
